version: "3"
services:
  postgres:
    image: postgres:11.5
    ports:
      - 5432:5432
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokedex_dev